/**
 * En-têtes FR dérivés 1:1 des fichiers d’exemple officiels PrestaShop
 * (`docs/csv_import/products_import.csv` et `combinations_import.csv`).
 * Libellés identiques à ceux du BO FR pour bénéficier de l’auto-mapping à l’import.
 */

/** Colonnes products.csv (ordre officiel PrestaShop). */
export const PRESTASHOP_PRODUCT_HEADERS = [
  "ID",
  "Actif (0/1)",
  "Nom *",
  "Catégories (x,y,z...)",
  "Prix hors taxe",
  "ID règle de taxe",
  "Prix d'achat",
  "En solde (0/1)",
  "Montant de la réduction",
  "Pourcentage de réduction",
  "Réduction du (aaaa-mm-jj)",
  "Réduction au (aaaa-mm-jj)",
  "Référence #",
  "Référence fournisseur #",
  "Fournisseur",
  "Marque",
  "EAN13",
  "ISBN",
  "UPC",
  "MPN",
  "Écotaxe",
  "Largeur",
  "Hauteur",
  "Profondeur",
  "Poids",
  "Délai de livraison pour produits en stock",
  "Délai de livraison pour produits hors stock avec commande autorisée",
  "Quantité",
  "Quantité minimale",
  "Niveau de stock bas",
  "Recevoir une alerte de stock bas par e-mail",
  "Emplacement du stock",
  "Visibilité",
  "Frais de port supplémentaires",
  "Unité",
  "Prix unitaire",
  "Résumé",
  "Description",
  "Tags (x,y,z...)",
  "Meta titre",
  "Meta description",
  "URL réécrite",
  "Texte si en stock",
  "Texte si commande en rupture autorisée",
  "Disponible à la commande (0 = Non, 1 = Oui)",
  "Date de disponibilité du produit",
  "Date de création du produit",
  "Afficher le prix (0 = Non, 1 = Oui)",
  "URL des images (x,y,z...)",
  "Textes alt des images (x,y,z...)",
  "Supprimer les images existantes (0 = Non, 1 = Oui)",
  "Caractéristique(Nom:Valeur:Position)",
  "Disponible uniquement en ligne (0 = Non, 1 = Oui)",
  "État",
  "Personnalisable (0 = Non, 1 = Oui)",
  "Fichiers téléchargeables (0 = Non, 1 = Oui)",
  "Champs texte (0 = Non, 1 = Oui)",
  "Action hors stock",
  "Produit virtuel",
  "URL du fichier",
  "Nombre de téléchargements autorisés",
  "Date d'expiration",
  "Nombre de jours",
  "ID / Nom de la boutique",
  "Gestion avancée du stock",
  "Dépend du stock",
  "Entrepôt",
  "Accessoires (x,y,z...)",
] as const;

/** Colonnes combinations.csv (ordre officiel PrestaShop). */
export const PRESTASHOP_COMBINATION_HEADERS = [
  "ID produit*",
  "Attribut (Nom:Type:Position)*",
  "Valeur (Valeur:Position)*",
  "Référence fournisseur",
  "Référence",
  "EAN13",
  "ISBN",
  "UPC",
  "Prix d'achat",
  "Impact sur le prix",
  "Écotaxe",
  "Quantité",
  "Quantité minimale",
  "Niveau de stock bas",
  "Impact sur le poids",
  "Défaut (0 = Non, 1 = Oui)",
  "Date de disponibilité de la déclinaison",
  "Position de l'image",
  "URL des images (x,y,z...)",
  "Textes alt des images (x,y,z...)",
  "ID / Nom de la boutique",
  "Gestion avancée du stock",
  "Dépend du stock",
  "Entrepôt",
] as const;

export type PrestashopProductHeader = (typeof PRESTASHOP_PRODUCT_HEADERS)[number];
export type PrestashopCombinationHeader = (typeof PRESTASHOP_COMBINATION_HEADERS)[number];
